### PR TITLE
Add cpt1 and kix1 serverless regions

### PR DESCRIPTION
**Pull request by chronark**
Hi friends, 

this adds Osaka and Cape Town regions to the available ones

### CODE REVIEW

**Review by dglsparsons — APPROVED** [review]

**Comment by dglsparsons** [comment]
Hey @chronark  - great spot and thanks for adding this 🙌

**Comment by chronark** [comment]
Wow that was quick, any eta on when this finds its way into the next release, @dglsparsons ?

**Comment by dglsparsons** [comment]
@chronark I've just pushed a v0.8.1 tag, so as soon as the release pipeline is done (usually ~10 minutes).

**Comment by dglsparsons** [comment]
And that should be available [now](https://github.com/vercel/terraform-provider-vercel/releases/tag/v0.8.1)! 🙌

**Comment by chronark** [comment]
Amazing, thank you

**Pull request merged**
